In [1]:
import numpy as np

# Generate a random vector of size 15 with integers in the range 1-20
rand_vec = np.random.randint(low=1, high=21, size=15)

print(rand_vec)


[17 11 15  4 14 12  6  1 18  1 14 11  2  5  3]


In [2]:
import numpy as np

# Generate a random vector of size 15 with integers in the range 1-20
rand_vec = np.random.randint(low=1, high=21, size=15)

# Reshape the vector into a 3 by 5 array
arr_3x5 = rand_vec.reshape((3, 5))

print(arr_3x5)


[[ 8  6 19 17  5]
 [ 2  3 17 19  5]
 [16 17 15 17 18]]


In [3]:
import numpy as np

# Generate a random vector of size 15 with integers in the range 1-20
rand_vec = np.random.randint(low=1, high=21, size=15)

# Reshape the vector into a 3 by 5 array
arr_3x5 = rand_vec.reshape((3, 5))

# Print the shape of the array
print(arr_3x5.shape)


(3, 5)


In [4]:
import numpy as np

# Generate a random vector of size 15 with integers in the range 1-20
rand_vec = np.random.randint(low=1, high=21, size=15)

# Reshape the vector into a 3 by 5 array
arr_3x5 = rand_vec.reshape((3, 5))

# Replace the max value in each row with 0
for i in range(arr_3x5.shape[0]):
    max_index = np.argmax(arr_3x5[i])
    arr_3x5[i][max_index] = 0

print(arr_3x5)


[[ 0  6  8 16 13]
 [ 9  0  2 17  2]
 [ 0  1  7  9  2]]
