In [1]:
import numpy as np

# Create a 2-dimensional array of size 4 x 3 with 4-byte integer elements
arr_4x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=np.int32)

# Print the shape of the array
print("Shape of the array:", arr_4x3.shape)

# Print the type of the array
print("Type of the array:", type(arr_4x3))

# Print the data type of the array
print("Data type of the array:", arr_4x3.dtype)

# Print the array
print(arr_4x3)


Shape of the array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array: int32
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
import numpy as np

# Define the square array
arr = np.array([[3, -2], [1, 0]])

# Compute the eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(arr)

# Print the eigenvalues and right eigenvectors
print("Eigenvalues:", eigenvalues)
print("Right eigenvectors:")
print(eigenvectors)


Eigenvalues: [2. 1.]
Right eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [3]:
import numpy as np

# Define the array
arr = np.array([[0, 1, 2], [3, 4, 5]])

# Compute the sum of the diagonal elements
diagonal_sum = np.trace(arr)

# Print the sum of the diagonal elements
print("Sum of the diagonal elements:", diagonal_sum)


Sum of the diagonal elements: 4


In [4]:
import numpy as np

# Define the original array
arr = np.array([[1, 2], [3, 4], [5, 6]])

# Reshape the array to 2x3
new_arr = np.reshape(arr, (2, 3))

# Print the original and new arrays
print("Original array:")
print(arr)
print("New array:")
print(new_arr)


Original array:
[[1 2]
 [3 4]
 [5 6]]
New array:
[[1 2 3]
 [4 5 6]]
